import Header from "@/components/layout/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Noto_Sans, Roboto } from "next/font/google";
import "tw-elements-react/dist/css/tw-elements-react.min.css";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
